export function getProjectRoot(): string
export function getDistRoot(): string
export function getDistPath(): string
export function getBuildRoot(): string
export function getAppExecutableName(): string
export function getAppPlatform(): string
export function getAppEnvironment(): string
export function isDevelopment(): boolean
export function isWindows(): boolean
export function isLinux(): boolean
export function isDarwin(): boolean
