#!/usr/bin/env node

const path = require('path')
const eslint = require('eslint')
const chalk = require('chalk')

const shouldFix = process.argv.indexOf('--fix') > -1

const cli = new eslint.CLIEngine({
  cwd: path.dirname(__dirname),
  cache: true,
  fix: shouldFix,
})

const report = cli.executeOnFiles([
  './webpack/*.js',
  './scripts/**/*.{j,t}s?(x)',
  './app/*.js',
  './app/{src,test}/**/*.{j,t}s?(x)',
])

if (shouldFix) {
  eslint.CLIEngine.outputFixes(report)
}

console.log(cli.getFormatter()(report.results))

if (report.errorCount > 0) {
  console.error(
    chalk`{green → To fix some of these errors, run {underline yarn eslint:fix}}`
  )
}
